version: '3'
services: 
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules #leave this folder as is
      - ./server:/app #anytime our app tries to access anything inside /app it will be redirected to the server directory (except for node_modules)
  client:
      build:
        dockerfile: Dockerfile.dev
        context: ./client
      ports:
        - "3000:3000"
      volumes:
        - /app/node_modules
        - ./client:/app